public enum TokenType {
    // symbols
    RPAREN, LPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    COMMA, SEMICOLON, DOT, PLUS, MINUS, ASTERISK, SLASH,
    AND, OR, NOT, LT, GT, EQ,

    // literals
    NUMBER, STRING, IDENT,

    // keywords
    CONSTRUCTOR, CLASS, FUNCTION, METHOD, STATIC, FIELD, VAR, INT,
    CHAR, BOOLEAN, VOID, TRUE, FALSE, NULL, THIS, LET, IF, DO, ELSE, WHILE, RETURN,

    EOF,
}
